### ISSUE TITLE
No such file or directory: '/tmp/model-data/grace_hopper.jpg'

### ISSUE THREAD

**Issue by kylethorpe** [bitnami/bitnami-docker-tensorflow-serving#8]
**Description**

When I try to run Step 4 of using the command line, I get the error:

`No such file or directory: '/tmp/model-data/grace_hopper.jpg'`

I have placed this image in that directory, I know it is definitely there.

**Steps to reproduce the issue:**

1. `docker pull bitnami/tensorflow-serving:latest`
2. Step 1 of Using the Command Line
3. `docker network create app-tier --driver bridge`
4. Step 3 of Using the Command Line
5. Step 4 of Using the Command Line

**Describe the results you received:**

```
D1123 00:50:54.936540912      10 ev_posix.c:101]             Using polling engine: poll
Traceback (most recent call last):
  File "/opt/bitnami/tensorflow-inception/bazel-bin/tensorflow_serving/example/inception_client.runfiles/tf_serving/tensorflow_serving/example/inception_client.py", line 55, in <module>
    tf.app.run()
  File "/opt/bitnami/tensorflow-inception/bazel-bin/tensorflow_serving/example/inception_client.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/opt/bitnami/tensorflow-inception/bazel-bin/tensorflow_serving/example/inception_client.runfiles/tf_serving/tensorflow_serving/example/inception_client.py", line 42, in main
    with open(FLAGS.image, 'rb') as f:
IOError: [Errno 2] No such file or directory: '/tmp/model-data/grace_hopper.jpg'
```

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

- Output of `docker info`:

```
Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 11
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: E23Y:OUIB:5RDU:AKGC:UX5F:44BR:44HB:WUU6:YD42:NV3E:VGAI:V7XJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 34
 Goroutines: 59
 System Time: 2018-11-23T00:59:42.650111054Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Using Docker for MAC

**Comment by andresbono** [comment]
Hi @kylethorpe, if you mounted the volumes as explained in the steps (`--volume /tmp/model-data:/bitnami/model-data`) you should find the image in `/bitnami/model-data/` inside the container. Can you try that path?

```
docker run -it --rm --volume /tmp/model-data:/bitnami/model-data  --network app-tier bitnami/tensorflow-inception:latest inception_client --server=tensorflow-serving:8500 --image=/bitnami/model-data/grace_hopper.jpg
```

**Comment by kylethorpe** [comment]
@andresbono 

Thanks for the response!
Just tried that, here's what I got:
`IOError: [Errno 2] No such file or directory: '/bitnami/model-data/grace_hopper.jpg'`

**Comment by andresbono** [comment]
Hi @kylethorpe, we can reproduce the issue.

After starting `tensorflow-serving` container you need to export the data model that you downloaded. That can be done by running the `tensorflow-inception` container in background mode:

```
docker run -d --rm --volume /tmp/model-data:/bitnami/model-data --network app-tier bitnami/tensorflow-inception:latest
```

Then, you need to check the `tensorflow-serving` logs by executing:

```
docker logs tensorflow-serving -f
```

It will show the following message. It may take some time to be ready and it will retry until it succeeds:

```
Successfully loaded servable version {name: inception version: 1}
```

Then, you can query the server to recognize the image:

```
docker run -it --rm --volume /tmp/model-data:/bitnami/model-data --network app-tier bitnami/tensorflow-inception:latest inception_client --server=tensorflow-serving:8500 --image=/bitnami/model-data/g.jpg
```

**Comment by andresbono** [comment]
@kylethorpe we have improved the README to better describe the steps to perform. Let us know if it solves the issue!
